complete bak -s i -l interactive -d 'prompt before overwrite'
complete bak -s t -l time -d 'add time to backup name'
complete bak -s m -l mv -d 'use mv to bak/restore file/directory'
complete bak -s r -l restore -d 'restore file/directory'
complete bak -r -f -s s -l suffix -d 'special a suffix, default: .bak'
complete bak -s h -l help -d 'print this help message'
